### ISSUE TITLE
`$.after` is broken.

### ISSUE THREAD

**Issue by Cerbrus** [nathan-osman/sechatr#2]
`$.after` doesn't work properly after [`chatstatus.js` modifies it](https://github.com/j-f1/forked-sechatr/blob/master/src/static/js/chatstatus.js#L169), if you pass plain text to the function, which means workarounds [like this](https://github.com/Charcoal-SE/userscripts/commit/bd0eb2bb036953a09777cd29ecb4e40ad08047fc#diff-14d1937e50db00ce8b8d61963f407cff) have to be used in other userscripts, if sechatr is installed as well.

Modifications made from `chatstatus.js` shouldn't affect other scripts.

JF submitted [a pull request](https://github.com/nathan-osman/sechatr/pull/1) catches exceptions thown by this.

However, since `.after()` is only used _once_ in this whole repository, I'd suggest moving the overridden functionality to [that specific line](https://github.com/nathan-osman/sechatr/blob/00be8286e8cf9de2b7d48a0d44167077bd3aca86/src/static/js/chatstatus.js#L154), instead, [or just _renaming_ the override.](https://github.com/nathan-osman/sechatr/pull/3)

**Comment by nathan-osman** [comment]
Thanks for the explanation. I was meaning to ask about the pull request and inadvertently forgot about it. I'll take a look at this shortly.

**Comment by nathan-osman** [comment]
I think I understand the problem now but the reason that `.after()` was originally overridden was due to the way that new messages are added.

The SE chat code inserts new messages by doing something like this:

    $('.messages').last().after(newMessage);

sechatr inserts the user icons immediately after messages in the DOM (they are adjacent siblings), so when the above line of code runs, the new messages are inserted _between_ the existing message and the user icons that my script inserts. This is not the intended behavior, hence the need to "hook" `.after()` and manually detach the user icons so that they can be reinserted in their correct location after the new messages are inserted.

The first pull request (that catches the exception) should do the trick. I hadn't intended for the `.after()` hook to have any side effects, so that's a bug. If there is a better way to accomplish what I described, I'm open to exploring other options. But this was the only method I could come up with that worked properly.
